#!/usr/bin/python3
# SPOx-FileCopyrightText: 2025 Yamada yuma j3371vkf@sit.ac.jp
import sys

ans = 0
for line in sys.stdin: 
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
