#!/usr/bin/python3
# SPOX-FileCopyrightText: 2025 Yamada yuma j3371vkf@sit.ac.jp
# SPOX-License-Identifier: BSD-3-Clause
import sys

ans = 0
for line in sys.stdin: 
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
